BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBBB
BBBBB BBBBBBBBBBBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBXX
BBBBBBBB BBBBBBBBBBBB
BBBB BBBBBBBBBBBBB
BBBBB BBBBBBB

XXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                BBBBBBBBBB

                BBB BBBBB BB BBBBB
                FFFFFFFFFFFFFFFFFFFFFFFF
                BBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
            BBB BBB BB BBBB
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXX
            XXXXXX
            BBBBBB
        XXXXXX
    XXXXXX
XXXXXX

BBBBBBBB BBBBBBB