BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBBB
BBBBB BBBBBBBBBBBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBXX
BBBBBBBB BBBBBBBBBBBB
BBBB BBBBBBBBBBBBB
BBBBB BBBBBBB

XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX
    XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX
        XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXX
    XXXXXX XXX
    XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX

        BBBBBBBBBB

        BBB BBBBB BB BBBBBBBBB
        XXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXX
            FFFFFFFFFFFFFFFFFFFFFFFF
        XXXXXX
        BBBBBB

        BBB BBBBB BB BBBBBBBBBBBB
        XXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXX
            FFFFFFFFFFFFFFFFFFFFFFFF
        XXXXXX
        BBBBBB

        XXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX

    XXXXXXX
XXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBXXXXXXXXXXX

BBBBBBBB BBBBBBB