BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBBB
BBBBB BBBBBBBBBBBB
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBXX
BBBBBBBB BBBBBBBBBBBB
BBBB BBBBBBBBBBBBB
BBBBB BBBBBBB
XXXX XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBXXXXXXXXXXX XXX
XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        
        BBBBBBBBBB
        
        BBB BBBBB BB BBBBBBBBB
        XXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
            FFFFFFFFFFFFFFFFFFFFFFFF
        XXXXXX
        BBBBBB
        
        BBB BBBBB BB BBBBBBBBBBBB
        XXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
            FFFFFFFFFFFFFFFFFFFFFFFF
        XXXXXX
        BBBBBB

        XXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXX
        XXXXXX
        
    XXXXXXX
XXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBXXXXXXXXXXX

BBBBBBBB BBBBBBB