BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBBB
BBBBB BBBBBBBBBBBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBXX
BBBBBBBB BBBBBBBBBBBB
BBBB BBBBBBBBBBBBB
BBBBB BBBBBBB

XXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX
        BBB BBBBBB BB BBBBBBB
        XXXX XXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX
        BBBBBB
    XXXXXX
XXXXXX

BBBBBBBB BBBBBBB