BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBBB
BBBBB BBBBBBBBBBBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBXX
BBBBBBBB BBBBBBBBBBBB
BBBB BBBBBBBBBBBBB
BBBBB BBBBBBB

XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                BBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX

                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                XXXXXX

                BBB BBBBB BB BBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXX
                    FFFFFFFFFFFFFFFFFFFFFFFF
                XXXXXX
                BBBBBB

                XXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXX
            
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXXX
        XXXXXX
    XXXXXX
XXXXXX
XXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXX
    XXXXXX

    XXXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX
                        XXX XXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX
                        XXX XXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                        XXXXX
                        XXX XXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX
                    XXXXX
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
                XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
            XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX
        XXXXXX
    XXXXXXX
XXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBXXXXXXXXXXX

BBBBBBBB BBBBBBB