# Generated by Django 2.1.7 on 2019-03-20 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('read_file', models.FileField(upload_to='materials/', verbose_name='Методичка')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Лабораторная работа',
                'verbose_name_plural': 'Лабораторные работы',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_executor', models.CharField(max_length=100, verbose_name='Исполнитель')),
                ('group', models.CharField(max_length=10, verbose_name='Группа')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('file', models.FileField(upload_to='reports/', verbose_name='Отчёт')),
                ('status', models.CharField(choices=[('Зачёт', 'Зачёт'), ('На проверке', 'На проверке'), ('Незачёт', 'Незачёт')], default='Незачёт', max_length=100)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.Subject')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.Profile')),
            ],
            options={
                'verbose_name': 'Отчёт',
                'verbose_name_plural': 'Отчёты',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('file', models.FileField(upload_to='tests/', verbose_name='Файл')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
    ]
