# Generated by Django 2.1.7 on 2019-03-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_accept',
            field=models.BooleanField(default=False, verbose_name='Зачтено'),
        ),
    ]
