# Generated by Django 2.1.7 on 2019-03-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_education', '0003_auto_20190319_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='is_accept',
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Зачёт', 'Зачёт'), ('На проверке', 'На проверке'), ('Незачёт', 'Незачёт')], default='Незачёт', max_length=100),
        ),
    ]
