# Generated by Django 2.1.7 on 2019-03-20 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20190319_1953'),
        ('virtual_education', '0004_auto_20190319_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('read_file', models.FileField(upload_to='materials/', verbose_name='Методичка')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Лабораторная работа',
                'verbose_name_plural': 'Лабораторные работы',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('file', models.FileField(upload_to='tests/', verbose_name='Файл')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
    ]
