# Generated by Django 2.1.7 on 2019-02-26 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('option', models.CharField(choices=[('winner', 'Призёр'), ('participant', 'участник')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ItCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('logo', models.ImageField(blank=True, upload_to='companies/logo', verbose_name='Логотип')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('m', 'Мужской'), ('g', 'Женский')], max_length=1, verbose_name='Пол')),
                ('group', models.CharField(max_length=10, verbose_name='Группа')),
                ('mark', models.CharField(default='0.0', max_length=3, verbose_name='Средний балл')),
                ('achievements', models.ManyToManyField(to='authentication.Achievement', verbose_name='Достижения')),
                ('career', models.ManyToManyField(to='authentication.ItCompany', verbose_name='Карьера')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Название')),
                ('logo', models.ImageField(blank=True, upload_to='technologies/logo', verbose_name='Логотип')),
                ('option', models.CharField(choices=[('lang', 'Язык программирования'), ('cms', 'CMS Система'), ('tool', 'Инструмент'), ('engine', 'Движок'), ('database', 'База данных')], max_length=10, verbose_name='Тип')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_subject',
            field=models.ManyToManyField(to='authentication.Subject', verbose_name='Любимые предметы'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(to='authentication.Technology', verbose_name='Стек технологий'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
