# Generated by Django 2.1.5 on 2019-03-19 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('virtual_education', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('option', models.CharField(choices=[('Призер', 'Призёр'), ('Участник', 'Участник')], max_length=20)),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
            },
        ),
        migrations.CreateModel(
            name='ItCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('logo', models.ImageField(blank=True, upload_to='companies/logo', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, verbose_name='Мобильный телефон')),
                ('sex', models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=10, verbose_name='Пол')),
                ('group', models.CharField(max_length=10, verbose_name='Группа')),
                ('mark', models.CharField(default='0.0', max_length=3, verbose_name='Средний балл')),
                ('photo', models.ImageField(blank=True, upload_to='photos', verbose_name='Аватар')),
                ('achievements', models.ManyToManyField(to='authentication.Achievement', verbose_name='Достижения')),
                ('career', models.ManyToManyField(to='authentication.ItCompany', verbose_name='Карьера')),
            ],
            options={
                'verbose_name': 'Личные данные',
                'verbose_name_plural': 'Личные данные',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Название')),
                ('logo', models.ImageField(blank=True, upload_to='technologies/logo', verbose_name='Логотип')),
                ('option', models.CharField(choices=[('Язык программирования', 'Язык программирования'), ('CMS', 'CMS Система'), ('Инструмент', 'Инструмент'), ('Движок', 'Движок'), ('База данных', 'База данных')], max_length=30, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Технология',
                'verbose_name_plural': 'Технологии',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_subject',
            field=models.ManyToManyField(to='authentication.Subject', verbose_name='Любимые предметы'),
        ),
        migrations.AddField(
            model_name='profile',
            name='reports',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='virtual_education.Report', verbose_name='Отчёты'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(to='authentication.Technology', verbose_name='Стек технологий'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
