# Generated by Django 2.1.7 on 2019-02-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='option',
            field=models.CharField(choices=[('Язык программирования', 'Язык программирования'), ('CMS', 'CMS Система'), ('Инструмент', 'Инструмент'), ('Движок', 'Движок'), ('База данных', 'База данных')], max_length=20, verbose_name='Тип'),
        ),
    ]
