# Generated by Django 2.1.7 on 2019-02-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='80296516350', max_length=15, verbose_name='Мобильный телефон'),
            preserve_default=False,
        ),
    ]
