# Generated by Django 2.1.7 on 2019-03-19 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_education', '0002_report_is_accept'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='reports',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='virtual_education.Report'),
        ),
    ]
