# Generated by Django 2.1.7 on 2019-03-19 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_subject_reports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='reports',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='reports',
        ),
    ]
