# Generated by Django 2.1.7 on 2019-03-19 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_education', '0001_initial'),
        ('authentication', '0003_auto_20190227_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reports',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='virtual_education.Report', verbose_name='Отчёты'),
            preserve_default=False,
        ),
    ]
