# Generated by Django 2.1.7 on 2019-02-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20190227_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos', verbose_name='Аватар'),
        ),
    ]
